export const products = [
  {
    id: 1,
    name: "Laptop Pro 15",
    category: "Electronics",
    price: 1400,
    image: "/products/laptop-3.webp",
  },
  {
    id: 2,
    name: "The Great Gatsby",
    category: "Books",
    price: 15,
    image: "/products/the-great-gatsby.webp",
  },
  {
    id: 3,
    name: "Classic T-Shirt",
    category: "Clothing",
    price: 20,
    image: "/products/tshirt.webp",
  },
  {
    id: 4,
    name: "Smartphone Ultra",
    category: "Electronics",
    price: 899,
    image: "/products/phone.webp",
  },
  {
    id: 5,
    name: "Atomic Habits",
    category: "Books",
    price: 18,
    image: "/products/atomic-habits.webp",
  },
  {
    id: 6,
    name: "Premium Hoodie",
    category: "Clothing",
    price: 45,
    image: "/products/hoodie.webp",
  },
  {
    id: 7,
    name: "Smartwatch Series 5",
    category: "Electronics",
    price: 250,
    image: "/products/smart-watch.jpg",
  },
  {
    id: 8,
    name: "Sapiens: A Brief History",
    category: "Books",
    price: 22,
    image: "/products/sapiens.jpg",
  },
  {
    id: 9,
    name: "Blue Denim Jeans",
    category: "Clothing",
    price: 55,
    image: "/products/jeans.webp",
  },
  {
    id: 10,
    name: "Gaming Laptop X",
    category: "Electronics",
    price: 1800,
    image: "/products/laptop-2.webp",
  },
  {
    id: 11,
    name: "Clean Code",
    category: "Books",
    price: 30,
    image: "/products/the-clean-code.webp",
  },
  {
    id: 12,
    name: "Wireless Headphones",
    category: "Electronics",
    price: 199,
    image: "/products/headphones.webp",
  },
  {
    id: 13,
    name: "Casual Sneakers",
    category: "Clothing",
    price: 70,
    image: "/products/sneakers.jpg",
  },
  {
    id: 14,
    name: "The Psychology of Money",
    category: "Books",
    price: 20,
    image: "/products/psychology-of-money.jpg",
  },
  {
    id: 15,
    name: "Jacket",
    category: "Clothing",
    price: 25,
    image: "/products/jacket.webp",
  },
];
